### ISSUE TITLE
專案中同時有多份不同版本的 hahow-design，其 styled-component 樣式可能會消失

### ISSUE THREAD

**Issue by choznerol** [hahow/hahow-design#13]
嚴格來說這是個 hahow-for-business 的 bug，但因為跟 hahow-design 比較有關，所以還是開在這

在 https://github.com/rubychi/hahow-for-business/commit/0f5dfeeca9fdfff83ee646ed41831e964788e1c3 之後可以觀察到此 bug

## 預期行為
來自  hahow-desgin 的 `<Button>` 正常顯示
> <img width="250" alt="Screen Shot 2020-01-20 at 4 05 32 PM" src="https://user-images.githubusercontent.com/12410942/72713495-19b41c00-3ba8-11ea-921e-3fc12b233702.png">

## 實際行為
如果進入的網址是課程頁，`<Button>` 就會變下圖這樣
> <img width="250" alt="Screen Shot 2020-01-20 at 4 06 35 PM" src="https://user-images.githubusercontent.com/12410942/72713493-191b8580-3ba8-11ea-87cd-91fe839dc3c3.png">

但如果先進首頁在點 `<InertiaLink>` 進課程頁，就會正常

## 推測
https://github.com/rubychi/hahow-for-business/commit/0f5dfeeca9fdfff83ee646ed41831e964788e1c3 最明顯的改變就是從 v0.10.5 升到 v0.11.0，但https://github.com/hahow/hahow-design/compare/v0.10.5...v0.11.0 看起來顯然沒有什麼會導致此 bug 的 code

後來發現是因為 hahow-for-business 同時有 2 個版本的 hahow-design 導致，原因是當時用的 hh-classroom 依賴 v0.10.5 的 hahow-design，而 hahow-for-business 依賴 v0.11.0 的 hahow-design ，於是就[兩個都各裝了一份](https://github.com/rubychi/hahow-for-business/blob/0f5dfeeca9fdfff83ee646ed41831e964788e1c3/yarn.lock#L1159-L1191)

**Comment by choznerol** [comment]
https://github.com/hahow/hahow-for-business/pull/714 merged 了，這邊也先關掉~

**Comment by amowu** [comment]
Sorry 正常嘗試其它的解法，不然之後兩邊都要同一個版本挺麻煩的 囧

**Comment by amowu** [comment]
[memo] 感覺跟這個問題很像 https://github.com/styled-components/styled-components/issues/2254

**Comment by choznerol** [comment]
我沒留意當時有沒有 `serveral instances of 'styled-component' initialized` 這個錯誤訊息，需要我切回去看看嗎？
https://github.com/styled-components/styled-components/issues/2254#issuecomment-463052398

**Comment by choznerol** [comment]
> Q: I am a library author. Should I bundle styled-components with my library?
> A: If you are a library author, we recommend that you should not bundle and ship styled-components module with your library. There are two steps that you need to do to achieve this:
>
> 來自 [styled-components: FAQ](https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library)

@amowu hahow-design 目前應該是連 styled-component 一起打包進去？

**Comment by amowu** [comment]
> A rarer problem is conflicts between two instances of styled-components on the page. You can avoid this by defining process.env.SC_ATTR in the code bundle with your styled-components instance. This value overrides the default <style> tag attribute, data-styled (data-styled-components in v3 and lower), allowing each styled-components instance to recognize its own tags.

https://styled-components.com/docs/advanced

試著照做，加入 `process.env.SC_ATTR`：

```js
environment.plugins.prepend(
  'DefinePlugin',
  new webpack.DefinePlugin({
    'process.env.SC_ATTR': '"foobar"'
  })
);
```

結果還是不 work，樣式競爭，前面的被清空：

![Screen Shot 2020-01-21 at 4 04 15 PM](https://user-images.githubusercontent.com/559351/72786150-d6b97d80-3c67-11ea-80ea-719e3ed1ac22.png)

@choznerol 不過進首頁的都會 work（包含接下來一系列走 inertial），但是從其他頁面重整（包括登入頁）都不 work，也沒有可能 webpack 只對首頁做過什麼設定嗎？

**Comment by amowu** [comment]
> hahow-design 目前應該是連 styled-component 一起打包進去？

@choznerol Yes

**Comment by amowu** [comment]
咦，我好像找到解決方法了

**Comment by amowu** [comment]
[memo] 解決方式：保持所有 packages 使用相同版本（至少 major 相同）的 styled-components
